### ISSUE TITLE
Uncaught TypeError: order_icon is null

### ISSUE THREAD

**Issue by jalsco** [VFDouglas/HTML-Order-Table-By-Column#1]
Hi Vicentini, (@VFDouglas  )

Thank you for developing this 🙏🏻 And also for posting about it on [StackOverflow](https://stackoverflow.com/questions/10683712/html-table-sort)

I am **not** a JS developer, so I am probably making some very obvious and basic mistakes.  Please help me to get it working for my page.  I think the problem is how I am calling your code (please check).  I mean, I think I am passing the wrong thing to your code - as in - not what your code is expecting to get ?

I stored your code in its own file, as a `function()` , and a`eventListener` to call it  

Here is (part of) my table definition: 
```
<table role="grid">
<thead>
<tr>
<th style="white-space: nowrap;">ID <span>↑</span></th>
<th>First Name</th><th>Last Name</th>
<th style="white-space: nowrap;">Birth Date<span>↑</span></th>
<th>Age now</th>
<th style="white-space: nowrap;">Test Date<span>↑</span>
</th><th>Age test</th>
```
Only 3 columns are for Sorting, and they are setup with `<span>` as per your example.  I have also confirmed the event listener is correctly attached, and correctly firing, and calling the function like this: 
```   
const ths = table.querySelectorAll('th');  
    for (const th of ths) {
        if (["ID ", "Bir", "Tes"].includes(th.innerText.substring(0, 3))) {
            th.style.whiteSpace = 'nowrap';
        }
        if (["ID ", "Bir", "Tes"].includes(th.innerText.substring(0, 3))) {
            th.addEventListener('click', (e) => OrderTableByColumn(e.target)); // event listener for selected column heading
        }
    }
```

The start of your code is like this:
```
function OrderTableByColumn(element) {

                let table = element.closest('table');
                let order_icon = element.querySelector('span');

                let order = encodeURI(order_icon.innerHTML).includes('%E2%86%91') ? 'desc' : 'asc';
```

But it gives me a `Uncaught TypeError: order_icon is null` when I click on the Column Heading.

**Comment by VFDouglas** [comment]
Fixed. Please take a look at the updated code. 

I just added an `if` to check if the column has the sort icon.

**Comment by jalsco** [comment]
Hi Vicentini, (@VFDouglas )

Thank you for fixing that 🙏🏻😁 - I confirm is working and sorting on my 3 columns.  

Two other comments about your code: 


1.  Using `this.` - As your code is in-line, `this.` will refer to the Global Object. However that is not true if your code in encased in a `function()` .   So I replaced `this.querySelector` with `element.querySelector`

2.  the `closest` function -  is not a method of the window object, its a method of the DOM element, and it's not cross-browser supported, you maybe should use other methods like parentNode or parents to reach the table parent element. So I rewrite `matches` like this : 
```
function closest(el, selector) {
    while (el) {
        if (el.matches(selector)) {
            return el;
        }
        el = el.parentNode;
    }
    return null;
}
```
I have your code with minor changes in first few lines only, like this : 
```
           function OrderTableByColumn(element) {

               function closest(el, selector) {
                   while (el) {
                       if (el.matches(selector)) {
                           return el;
                       }
                       el = el.parentNode;
                   }
                   return null;
               }

               let table = element.closest('table');
               let order_icon = element.querySelector('span');


               // If the column is sortable
               if (element.querySelector('span')) {
                   let order_icon = element.querySelector('span');

                   let order = encodeURI(order_icon.innerHTML).includes('%E2%86%91') ? 'desc' : 'asc';
               //  all the rest of the cost is unchanged
   
```

**Comment by VFDouglas** [comment]
@jalsco 

1. In the demo file, `this` refer to the clicked `<th>` element, so that's why I chose to use it. And the main purpose is to use this code for multiple tables, so you don't need to bind functions to them when you create another.
**P.S.:** Thanks to the issue you submitted, only tables with the sort icons will be affected.
2. The `closest` function is pretty much accepted between browsers. Are you using some browser below of one of these versions?
https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#browser_compatibility

**Comment by jalsco** [comment]
Yeah, iOS Safari is diabolic sometimes. Thanks for your concern about the crazy stuff I must support sometime 😊😂

Although I only support modern versions ( Firefox, Chrome, Edge) for non-mobile devices, I do have problem to support old iOS back to v9. 

 But that's really not the problem about `closest`. .. It has he opposite problem.  Meaning even if there is/was past support, as it is non-standard, the support for it in future Browser versions cannot be assumed.  I don't really know.....  However, I do know that table sorting is working for me now , on all my test devices and test  Browsers. **And for that - I thank you 🙏🏻**

I was sent this  :  _closest is a non-standard method in JavaScript, which means that it is not part of the official DOM API (Document Object Model API) and is not supported by all browsers. It was first introduced by Microsoft as an extension to the Internet Explorer DOM and then later adopted by other browsers such as Google Chrome and Firefox._

**Comment by VFDouglas** [comment]
Ahh I see now. Unfortunately almost every language has compatibility issues. 
But since you're using functions to fire the sorting, another solution instead of `element.parentNode.parentNode.parentNode` is to add the table id as a parameter, so you can call directly `let table = document.getElementById(table_id)`.

The purpose of this repository was for my future use, but it's very good to know I helped someone.
Have a great day!

**Comment by jalsco** [comment]
You have really helped me **A LOT !** 🙏🏻🙏🏻🙏🏻  I am just a beginner in JS.
  
Going forward, **maybe** I will add table id for each table, as it simplifies the code, as you pointed out,  to: `let table = document.getElementById(table_id)`.  

But I do love the way you are doing it, so table ID is not even needed.  It is working for me now ( including for multiple tables ), so I probably won't change it.  Thanks for the great tips ! 

p.s. I tried 3 other code snippets before yours. All of those had problems, or did not work or did not work fully, or were slow, or too complicated, or had dependencies. Yours is by far the best. 

Thank you again ! 😁🙏🏻
